# Generated by Django 2.1 on 2018-08-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('fazenda', models.CharField(max_length=30)),
                ('hectares', models.FloatField()),
                ('cultura', models.CharField(choices=[('SOJA', 'Produção de soja'), ('ALGODAO', 'Produção de algodão'), ('MILHO', 'Produção de milho')], max_length=50)),
                ('disponivel', models.BooleanField(default=1)),
            ],
        ),
    ]
